### PR TITLE
refactor: change dependencies `glob-all` to `glob`

### PR DESCRIPTION
**Pull request by aaharu**
I think that it's enough to use `glob`.

### CODE REVIEW

**Comment by manniL** [comment]
Does it make a huge difference? :thinking: :relaxed: 
What are pros/cons of this change?

**Comment by aaharu** [comment]
pros
* reducing package size
  * `glob-all` requires `"glob": "^7.0.5","yargs": "~1.2.6"` and yargs@1.2.6 requires `minimist`

cons
* change in behavior
  * Is this behavior intentional?
```js
// OK
styleResources: {
  scss: './assets/vars/*.scss'
}
// OK
styleResources: {
  scss: [
    './assets/vars/*.scss',
    './assets/abstracts/_mixins.scss'
  ]
}
// OK
styleResources: {
  scss: [
    './assets/vars/*.scss',
    './assets/vars2/*.scss',
    './assets/vars3/*.scss',
    './assets/abstracts/_mixins.scss'
  ]
}

// NG ( `glob-all` works, but `glob` doesn't )
styleResources: {
  scss: [
    [
      './assets/vars/*.scss',
      './assets/vars2/*.scss',
      './assets/vars3/*.scss'
    ],
    './assets/abstracts/_mixins.scss'
  ]
}
```

https://github.com/nuxt-community/style-resources-module/blob/e1754ede42a65f9d9127e0310b4ed09d7ba83232/lib/module.js#L30-L44

**Comment by manniL** [comment]
An array of glob patterns is intended because variables could reside in different folders. :relaxed: 

`glob` doesn't support that out of the box, right?

**Comment by aaharu** [comment]
> An array of glob patterns is intended because variables could reside in different folders.

I couldn't read from the documentation...

**Comment by aaharu** [comment]
If it is a specification, I thought that it was not necessary to change it now.
Thank you for your review.

**Pull request closed without merging**
